name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm install --omit=dev
      - id: vars
        # Adapted from https://github.com/marketplace/actions/branch-names
        run: |
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            REF=$(printf "%q" "${{ github.ref }}")
            TAG=${REF/refs\/tags\//}
            echo ::set-output name=version::$(echo ${TAG})
            echo ::set-output name=is_tag::true
          else
            echo ::set-output name=version::$(echo ${GITHUB_SHA})
            echo ::set-output name=is_tag::false
          fi
        shell: bash
      - run: |
          mkdir phpcacheadmin
          cp -r node_modules services index.js LICENSE.txt package.json package-lock.json README.md phpcacheadmin
          echo "${{ steps.vars.outputs.version }}" > phpcacheadmin/VERSION.txt
        shell: bash
      - uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: 'phpcacheadmin'
          filename: phpcacheadmin-${{ steps.vars.outputs.version }}.zip
      - uses: actions/upload-artifact@v3
        with:
          name: phpcacheadmin-${{ steps.vars.outputs.version }}
          path: phpcacheadmin-${{ steps.vars.outputs.version }}.zip
      - uses: softprops/action-gh-release@v1
        if: steps.vars.outputs.is_tag == 'true'
        with:
          draft: true
          files: phpcacheadmin-${{ steps.vars.outputs.version }}.zip
          generate_release_notes: true
